// ============================================================
// CENTRAL API TRANSPORT
// ============================================================
//
// FINAL AUTHENTICATION MODEL
//
// Frontend:
//   - Does NOT read JWT
//   - Does NOT store JWT
//   - Does NOT decide authentication
//
// Browser:
//   - Automatically sends HttpOnly auth cookie
//
// Backend:
//   - Verifies JWT
//   - Re-checks user from database
//   - Enforces authorization
//
// Database:
//   - Source of truth
// ============================================================

const PUBLIC_API_PATHS = new Set([
  "/api/login",
  "/api/register",
  "/api/health",
  "/api/db-test",
  "/api/db/test",
  "/api/email-test",
]);

let installed = false;

// ============================================================
// URL HELPERS
// ============================================================

function isApiRequest(url: string): boolean {
  return url.startsWith("/api/") || url.includes("/api/");
}

function getPathname(url: string): string {
  try {
    return new URL(url, window.location.origin).pathname;
  } catch {
    return url;
  }
}

function isPublicApiPath(pathname: string): boolean {
  if (PUBLIC_API_PATHS.has(pathname)) {
    return true;
  }

  // ----------------------------------------------------------
  // Dynamic activation URL
  //
  // /api/activate/:token
  //
  // Activation does NOT require authentication.
  // ----------------------------------------------------------

  if (pathname.startsWith("/api/activate/")) {
    return true;
  }

  return false;
}

// ============================================================
// SESSION PROBE PATHS
// ============================================================
//
// These endpoints are used to CHECK authentication state.
//
// IMPORTANT:
//
// A 401 from /api/me does NOT mean an already-authenticated
// session has expired.
//
// It can simply mean:
//     "There is no existing session."
//
// Therefore /api/me MUST NEVER trigger amp:auth-expired.
//
// ============================================================

function isSessionProbePath(pathname: string): boolean {
  return pathname === "/api/me";
}

// ============================================================
// AUTH SESSION HELPERS
// ============================================================
//
// IMPORTANT:
//
// JavaScript cannot read the HttpOnly authentication cookie.
//
// Therefore getAuthToken() intentionally returns null.
//
// Authentication state is determined by:
//
//     GET /api/me
//
// ============================================================

/**
 * Compatibility helper.
 *
 * JWT is intentionally inaccessible to frontend JavaScript.
 */
export function getAuthToken(): null {
  return null;
}

/**
 * Clear client-side authentication state.
 *
 * There is intentionally NO localStorage authentication state.
 *
 * The actual HttpOnly cookie must be cleared by:
 *
 *     POST /api/logout
 *
 * This function only informs the application that the backend
 * session is no longer valid.
 */
export function clearAuthSession(): void {
  notifyAuthExpired();
}

// ============================================================
// AUTH EXPIRY EVENT
// ============================================================
//
// IMPORTANT:
//
// This event is ONLY for a protected API request which was made
// while the application already considers the user authenticated.
//
// It must NOT be generated by:
//
//     /api/me
//
// because /api/me is the initial/session-probe endpoint.
//
// ============================================================

function notifyAuthExpired(): void {
  if (typeof window === "undefined") {
    return;
  }

  window.dispatchEvent(new CustomEvent("amp:auth-expired"));
}

// ============================================================
// FETCH INSTALLATION
// ============================================================
//
// All browser API requests automatically include credentials.
//
// This means:
//
//     HttpOnly cookie → backend
//
// without exposing the JWT to JavaScript.
// ============================================================

export function installAuthenticatedFetch(): void {
  if (installed || typeof window === "undefined") {
    return;
  }

  installed = true;

  const originalFetch = window.fetch.bind(window);

  window.fetch = async (
    input: RequestInfo | URL,
    init: RequestInit = {},
  ): Promise<Response> => {
    const url =
      typeof input === "string"
        ? input
        : input instanceof URL
          ? input.toString()
          : input.url;

    const pathname = getPathname(url);

    const requestInit: RequestInit = {
      ...init,

      // --------------------------------------------------------
      // Critical:
      //
      // Browser automatically sends the HttpOnly authentication
      // cookie.
      // --------------------------------------------------------

      credentials: init.credentials || "include",
    };

    const response = await originalFetch(input, requestInit);

    // ----------------------------------------------------------
    // PROTECTED API SESSION EXPIRY
    // ----------------------------------------------------------
    //
    // A protected API returning 401 means the backend no longer
    // considers the current authenticated session valid.
    //
    // BUT:
    //
    // /api/me is a session probe and MUST NOT trigger this event.
    //
    // This prevents the initial /api/me request from racing with
    // a successful login and immediately logging the user out.
    // ----------------------------------------------------------

    if (
      isApiRequest(url) &&
      !isPublicApiPath(pathname) &&
      !isSessionProbePath(pathname) &&
      response.status === 401
    ) {
      notifyAuthExpired();
    }

    return response;
  };
}

// ============================================================
// AUTHORITATIVE SESSION VALIDATION
// ============================================================
//
// /api/me is the authoritative authentication check.
//
// No JWT is read.
// No localStorage session is read.
// No frontend role is trusted.
//
// IMPORTANT:
//
// A 401/403 from /api/me simply means that there is no valid
// existing backend session.
//
// It does NOT dispatch amp:auth-expired.
//
// ============================================================

export async function validateStoredSession(): Promise<boolean> {
  if (typeof window === "undefined") {
    return false;
  }

  try {
    const response = await window.fetch("/api/me", {
      method: "GET",
      headers: {
        Accept: "application/json",
      },
      credentials: "include",
    });

    if (response.ok) {
      return true;
    }

    if (response.status === 401 || response.status === 403) {
      // --------------------------------------------------------
      // IMPORTANT:
      //
      // Do NOT call notifyAuthExpired() here.
      //
      // /api/me is only a session probe.
      // --------------------------------------------------------

      return false;
    }

    // ----------------------------------------------------------
    // A 5xx/network problem does NOT prove that the session is
    // invalid.
    // ----------------------------------------------------------

    return false;
  } catch {
    // ----------------------------------------------------------
    // Network failure does not establish authentication.
    // ----------------------------------------------------------

    return false;
  }
}

// ============================================================
// INSTALL TRANSPORT
// ============================================================

installAuthenticatedFetch();

// ============================================================
// GENERIC JSON API HELPER
// ============================================================

export async function apiRequest<T>(
  input: RequestInfo | URL,
  init: RequestInit = {},
): Promise<T> {
  const requestHeaders = new Headers(init.headers || {});

  if (!requestHeaders.has("Accept")) {
    requestHeaders.set("Accept", "application/json");
  }

  if (init.body && !requestHeaders.has("Content-Type")) {
    requestHeaders.set("Content-Type", "application/json");
  }

  const response = await window.fetch(input, {
    ...init,

    // ----------------------------------------------------------
    // Always include the HttpOnly authentication cookie.
    // ----------------------------------------------------------

    credentials: init.credentials || "include",

    headers: requestHeaders,
  });

  const contentType = response.headers.get("content-type") || "";

  const data = contentType.includes("application/json")
    ? await response.json()
    : await response.text();

  if (!response.ok) {
    const message =
      typeof data === "object" && data !== null && "message" in data
        ? String(
            (
              data as {
                message: unknown;
              }
            ).message,
          )
        : `API request failed with status ${response.status}.`;

    const error = new Error(message) as Error & {
      status?: number;
      data?: unknown;
    };

    error.status = response.status;
    error.data = data;

    throw error;
  }

  return data as T;
}
