import nodemailer from "nodemailer";

import { CLIENT_URL, EMAIL_PASS, EMAIL_USER, PORT } from "../config/env";

// ============================================================
// AUTH EMAIL SERVICE
// ============================================================
//
// Backend-only email service for:
//   1. Registration activation link
//   2. Account activation confirmation
//
// IMPORTANT:
// - No localStorage
// - No frontend/window access
// - No authentication logic
// - No password handling
// - No database queries
//
// Registration / activation business logic remains in
// auth.service.ts.
// SMTP/email delivery remains here.
// ============================================================

const DEFAULT_CLIENT_URL = `http://localhost:${PORT}`;

/**
 * Normalize the configured frontend URL.
 */
function getClientUrl(): string {
  const configuredUrl = String(CLIENT_URL || "")
    .trim()
    .replace(/\/+$/, "");

  return configuredUrl || DEFAULT_CLIENT_URL;
}

/**
 * Create the SMTP transporter only when email credentials
 * are configured.
 */
function createMailTransporter() {
  if (!EMAIL_USER || !EMAIL_PASS) {
    return null;
  }

  return nodemailer.createTransport({
    service: "gmail",
    auth: {
      user: EMAIL_USER,
      pass: EMAIL_PASS,
    },
  });
}

/**
 * Escape user-controlled text before inserting it into HTML.
 */
function escapeHtml(value: string): string {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#039;");
}

/**
 * Build the activation URL.
 *
 * The token is generated by the backend auth service.
 */
function buildActivationLink(activationToken: string): string {
  const cleanToken = String(activationToken || "").trim();

  if (!cleanToken) {
    throw new Error(
      "Activation token is required to build the activation link.",
    );
  }

  return `${getClientUrl()}/activate/${encodeURIComponent(cleanToken)}`;
}

// ============================================================
// REGISTRATION ACTIVATION EMAIL
// ============================================================

export interface ActivationEmailInput {
  fullName: string;
  email: string;
  activationToken: string;
}

export interface EmailSendResult {
  success: boolean;
  message: string;
}

/**
 * Send account activation email after successful registration.
 */
export async function sendRegistrationActivationEmail(
  input: ActivationEmailInput,
): Promise<EmailSendResult> {
  const fullName = String(input.fullName || "").trim();
  const email = String(input.email || "")
    .trim()
    .toLowerCase();

  if (!fullName || !email || !input.activationToken) {
    throw new Error(
      "Activation email requires full name, email and activation token.",
    );
  }

  const transporter = createMailTransporter();

  if (!transporter) {
    throw new Error(
      "Email service is not configured. EMAIL_USER and EMAIL_PASS are required.",
    );
  }

  const activationLink = buildActivationLink(input.activationToken);

  const safeName = escapeHtml(fullName);
  const safeEmail = escapeHtml(email);

  await transporter.sendMail({
    from: `"Wildlife Institute of India" <${EMAIL_USER}>`,
    to: email,
    subject: "Activate Your WII Access Management Portal Account",

    text: `Dear ${fullName},

Welcome to the Wildlife Institute of India Access Management Portal.

Your account has been registered successfully.

Your account is currently inactive. Please activate your account using the link below:

${activationLink}

After activation, you can log in using your registered email address and password.

This email was sent to ${email}.

Regards,
Wildlife Institute of India
Access Management Portal`,

    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <title>Activate WII Portal Account</title>
      </head>

      <body
        style="
          margin:0;
          padding:0;
          background:#f1f5f9;
          font-family:Arial,Helvetica,sans-serif;
          color:#1e293b;
        "
      >
        <div
          style="
            max-width:640px;
            margin:32px auto;
            background:#ffffff;
            border-radius:12px;
            overflow:hidden;
            border:1px solid #e2e8f0;
          "
        >
          <div
            style="
              padding:24px;
              background:#0f172a;
              color:#ffffff;
            "
          >
            <h2
              style="
                margin:0;
                font-size:22px;
              "
            >
              WII Access Management Portal
            </h2>

            <p
              style="
                margin:8px 0 0;
                color:#cbd5e1;
                font-size:14px;
              "
            >
              Account Activation
            </p>
          </div>

          <div style="padding:28px 24px;">
            <p>
              Dear <strong>${safeName}</strong>,
            </p>

            <p>
              Your account has been successfully registered
              with the Wildlife Institute of India Access
              Management Portal.
            </p>

            <p>
              Your account is currently
              <strong>inactive</strong>.
              Please activate it using the button below.
            </p>

            <div
              style="
                margin:28px 0;
                text-align:center;
              "
            >
              <a
                href="${activationLink}"
                style="
                  display:inline-block;
                  padding:13px 22px;
                  background:#008f63;
                  color:#ffffff;
                  text-decoration:none;
                  border-radius:7px;
                  font-size:14px;
                  font-weight:bold;
                "
              >
                Activate My Account
              </a>
            </div>

            <p
              style="
                font-size:13px;
                color:#475569;
              "
            >
              If the button does not work, copy and open
              the following link in your browser:
            </p>

            <p
              style="
                word-break:break-all;
                font-size:13px;
                background:#f8fafc;
                border:1px solid #e2e8f0;
                padding:12px;
                border-radius:6px;
              "
            >
              ${activationLink}
            </p>

            <p
              style="
                font-size:13px;
                color:#475569;
              "
            >
              Once your account is activated, you can log in
              using your registered email address and password.
            </p>

            <p
              style="
                font-size:12px;
                color:#64748b;
                margin-top:24px;
              "
            >
              This message was sent to ${safeEmail}.
            </p>

            <p style="margin-top:28px;">
              Regards,<br />
              <strong>Wildlife Institute of India</strong><br />
              Access Management Portal
            </p>
          </div>
        </div>
      </body>
      </html>
    `,
  });

  return {
    success: true,
    message: "Account activation email sent successfully.",
  };
}

// ============================================================
// ACCOUNT ACTIVATION SUCCESS EMAIL
// ============================================================

export interface ActivationSuccessEmailInput {
  fullName: string;
  email: string;
}

/**
 * Send confirmation after a successful account activation.
 */
export async function sendActivationSuccessEmail(
  input: ActivationSuccessEmailInput,
): Promise<EmailSendResult> {
  const fullName = String(input.fullName || "").trim();
  const email = String(input.email || "")
    .trim()
    .toLowerCase();

  if (!fullName || !email) {
    throw new Error(
      "Activation confirmation email requires full name and email.",
    );
  }

  const transporter = createMailTransporter();

  if (!transporter) {
    throw new Error(
      "Email service is not configured. EMAIL_USER and EMAIL_PASS are required.",
    );
  }

  const loginLink = `${getClientUrl()}/login`;

  const safeName = escapeHtml(fullName);
  const safeEmail = escapeHtml(email);

  await transporter.sendMail({
    from: `"Wildlife Institute of India" <${EMAIL_USER}>`,
    to: email,
    subject: "WII Portal Account Activated Successfully",

    text: `Dear ${fullName},

Your Wildlife Institute of India Access Management Portal account has been activated successfully.

You can now log in using your registered email address and password.

Login:
${loginLink}

This email was sent to ${email}.

Regards,
Wildlife Institute of India
Access Management Portal`,

    html: `
      <!DOCTYPE html>
      <html lang="en">
      <head>
        <meta charset="UTF-8" />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        />
        <title>WII Account Activated</title>
      </head>

      <body
        style="
          margin:0;
          padding:0;
          background:#f1f5f9;
          font-family:Arial,Helvetica,sans-serif;
          color:#1e293b;
        "
      >
        <div
          style="
            max-width:640px;
            margin:32px auto;
            background:#ffffff;
            border-radius:12px;
            overflow:hidden;
            border:1px solid #e2e8f0;
          "
        >
          <div
            style="
              padding:24px;
              background:#0f172a;
              color:#ffffff;
            "
          >
            <h2 style="margin:0;">
              WII Access Management Portal
            </h2>

            <p
              style="
                margin:8px 0 0;
                color:#cbd5e1;
                font-size:14px;
              "
            >
              Account Activation Successful
            </p>
          </div>

          <div style="padding:28px 24px;">
            <p>
              Dear <strong>${safeName}</strong>,
            </p>

            <p>
              Your Wildlife Institute of India Access
              Management Portal account has been
              <strong>activated successfully</strong>.
            </p>

            <p>
              You can now log in using your registered
              email address and password.
            </p>

            <div
              style="
                margin:28px 0;
                text-align:center;
              "
            >
              <a
                href="${loginLink}"
                style="
                  display:inline-block;
                  padding:13px 22px;
                  background:#008f63;
                  color:#ffffff;
                  text-decoration:none;
                  border-radius:7px;
                  font-size:14px;
                  font-weight:bold;
                "
              >
                Go to Login
              </a>
            </div>

            <p
              style="
                font-size:13px;
                color:#64748b;
              "
            >
              Registered email:
              <strong>${safeEmail}</strong>
            </p>

            <p style="margin-top:28px;">
              Regards,<br />
              <strong>Wildlife Institute of India</strong><br />
              Access Management Portal
            </p>
          </div>
        </div>
      </body>
      </html>
    `,
  });

  return {
    success: true,
    message: "Account activation confirmation email sent successfully.",
  };
}
