import { mkdir, readFile, unlink, writeFile } from "node:fs/promises";
import path from "node:path";
import crypto from "node:crypto";
import type { PoolConnection } from "mysql2/promise";

import { db } from "../db/connection";
import {
  getProfileByUserIdWithConnection,
  upsertProfileWithConnection,
} from "../repositories/profile.repository";
import { recordProfileChangeWithConnection } from "../repositories/profile-history.repository";

/* ============================================================
   PROFILE PHOTO CONFIGURATION
   ============================================================ */

const MAX_PROFILE_PHOTO_SIZE = 5 * 1024 * 1024; // 5 MB

const PROFILE_PHOTO_DIRECTORY = path.resolve(
  process.cwd(),
  "uploads",
  "profile-photos",
);

const ALLOWED_EXTENSIONS = new Set(["jpg", "jpeg", "png", "webp"]);

/* ============================================================
   TYPES
   ============================================================ */

export interface ProfilePhotoFile {
  buffer: Buffer;
  mimetype: string;
  originalname: string;
  size: number;
}

export interface ProfilePhotoAuditContext {
  ipAddress?: string | null;
  userAgent?: string | null;
}

/* ============================================================
   FILE VALIDATION
   ============================================================ */

/**
 * Detect the actual image format from the file bytes.
 *
 * We do not trust the browser supplied MIME type alone.
 */
function detectImageExtension(buffer: Buffer): "jpg" | "png" | "webp" | null {
  /* JPEG */
  if (
    buffer.length >= 3 &&
    buffer[0] === 0xff &&
    buffer[1] === 0xd8 &&
    buffer[2] === 0xff
  ) {
    return "jpg";
  }

  /* PNG */
  if (
    buffer.length >= 8 &&
    buffer[0] === 0x89 &&
    buffer[1] === 0x50 &&
    buffer[2] === 0x4e &&
    buffer[3] === 0x47 &&
    buffer[4] === 0x0d &&
    buffer[5] === 0x0a &&
    buffer[6] === 0x1a &&
    buffer[7] === 0x0a
  ) {
    return "png";
  }

  /* WebP = RIFF....WEBP */
  if (
    buffer.length >= 12 &&
    buffer.toString("ascii", 0, 4) === "RIFF" &&
    buffer.toString("ascii", 8, 12) === "WEBP"
  ) {
    return "webp";
  }

  return null;
}

function validateUploadedPhoto(file: ProfilePhotoFile): "jpg" | "png" | "webp" {
  if (!file || !Buffer.isBuffer(file.buffer)) {
    throw new Error("Profile photo file is required.");
  }

  if (file.size <= 0 || file.buffer.length <= 0) {
    throw new Error("Profile photo cannot be empty.");
  }

  if (file.size > MAX_PROFILE_PHOTO_SIZE) {
    throw new Error("Profile photo must not exceed 5 MB.");
  }

  if (!ALLOWED_EXTENSIONS.has(getExtension(file.originalname))) {
    throw new Error("Profile photo must be a JPG, JPEG, PNG, or WebP image.");
  }

  const detectedExtension = detectImageExtension(file.buffer);

  if (!detectedExtension) {
    throw new Error("Uploaded file is not a valid supported image.");
  }

  const expectedMimeTypes: Record<"jpg" | "png" | "webp", string[]> = {
    jpg: ["image/jpeg"],
    png: ["image/png"],
    webp: ["image/webp"],
  };

  if (
    !expectedMimeTypes[detectedExtension].includes(file.mimetype.toLowerCase())
  ) {
    throw new Error("Uploaded image type does not match its file content.");
  }

  return detectedExtension;
}

/* ============================================================
   PATH HELPERS
   ============================================================ */

function getExtension(filename: string): string {
  const extension = path
    .extname(filename || "")
    .replace(".", "")
    .toLowerCase();

  return extension;
}

/**
 * Only controlled relative paths generated by this service
 * are allowed to be deleted.
 */
function getSafeStoredFilePath(
  storedPath: string | null | undefined,
): string | null {
  if (!storedPath) {
    return null;
  }

  const normalized = storedPath.replace(/\\/g, "/").replace(/^\/+/, "");

  const expectedPrefix = "uploads/profile-photos/";

  if (!normalized.startsWith(expectedPrefix)) {
    return null;
  }

  const filename = normalized.slice(expectedPrefix.length);

  if (
    !filename ||
    filename.includes("/") ||
    filename.includes("\\") ||
    filename.includes("..")
  ) {
    return null;
  }

  return path.join(PROFILE_PHOTO_DIRECTORY, filename);
}

/* ============================================================
   USER VALIDATION
   ============================================================ */

async function ensureActiveUser(
  connection: PoolConnection,
  userId: number,
): Promise<void> {
  const [rows]: any = await connection.query(
    `
        SELECT id
        FROM users
        WHERE id = ?
          AND status = 'active'
        LIMIT 1
      `,
    [userId],
  );

  if (!rows?.length) {
    throw new Error("User account is not active.");
  }
}

/* ============================================================
   PROFILE PHOTO SAVE
   ============================================================ */

export async function saveProfilePhoto(
  userId: number,
  file: ProfilePhotoFile,
  auditContext?: ProfilePhotoAuditContext,
) {
  if (!Number.isSafeInteger(userId) || userId <= 0) {
    throw new Error("Invalid user ID.");
  }

  const extension = validateUploadedPhoto(file);

  await mkdir(PROFILE_PHOTO_DIRECTORY, {
    recursive: true,
  });

  /*
   * Filename is generated by the server.
   *
   * The original filename is never used as the stored filename.
   */
  const filename = `${crypto.randomUUID()}.${extension}`;

  const storedRelativePath = `uploads/profile-photos/${filename}`;

  const storedAbsolutePath = path.join(PROFILE_PHOTO_DIRECTORY, filename);

  let newFileWritten = false;

  const connection: PoolConnection = await db.getConnection();

  try {
    await ensureActiveUser(connection, userId);

    const oldProfile = await getProfileByUserIdWithConnection(
      connection,
      userId,
    );

    /*
     * Write the new file before changing the DB.
     *
     * If the DB transaction fails, the newly written file
     * is removed in the catch block.
     */
    await writeFile(storedAbsolutePath, file.buffer, {
      flag: "wx",
    });

    newFileWritten = true;

    /*
     * A user can legitimately have a users row before the
     * applicant_profiles row has been initialized.
     *
     * The users table is authoritative for the mandatory
     * identity fields required to create the profile row.
     *
     * We therefore initialize the missing applicant profile
     * server-side instead of forcing the user to save the
     * profile form first or inserting data from the frontend.
     */
    let profileToSave = oldProfile;

    if (!profileToSave) {
      const [userRows]: any = await connection.query(
        `
          SELECT
            id,
            full_name,
            email,
            phone
          FROM users
          WHERE id = ?
            AND status = 'active'
          LIMIT 1
        `,
        [userId],
      );

      const user = userRows?.[0];

      if (!user) {
        throw new Error("User account is not active.");
      }

      profileToSave = {
        userId,
        applicantName: String(user.full_name).trim(),
        mobileNo: String(user.phone).trim(),
        personalEmail: String(user.email).trim().toLowerCase(),
        profilePhotoPath: storedRelativePath,
      };
    } else {
      profileToSave = {
        ...profileToSave,
        profilePhotoPath: storedRelativePath,
      };
    }

    await connection.beginTransaction();

    const savedProfile = await upsertProfileWithConnection(
      connection,
      profileToSave,
    );

    /*
     * Creating the missing profile row because of a photo upload
     * is a CREATE history event. Replacing an existing photo is
     * an UPDATE event.
     */
    await recordProfileChangeWithConnection(connection, {
      userId,
      changedByUserId: userId,
      actionType: oldProfile ? "UPDATE" : "CREATE",

      changedFields: {
        profilePhotoPath: true,
      },

      /*
       * Do not store the actual image or filesystem details in
       * audit history. Only the controlled application reference
       * is represented.
       */
      oldValues: {
        profilePhotoPath: oldProfile?.profilePhotoPath
          ? "[existing photo]"
          : null,
      },

      newValues: {
        profilePhotoPath: "[profile photo updated]",
      },

      ipAddress: auditContext?.ipAddress ?? null,

      userAgent: auditContext?.userAgent ?? null,
    });

    await connection.commit();

    /*
     * Remove the previous photo only after the DB transaction
     * has successfully committed.
     */
    const oldFilePath = getSafeStoredFilePath(oldProfile?.profilePhotoPath);

    if (oldFilePath && oldFilePath !== storedAbsolutePath) {
      await unlink(oldFilePath).catch(() => {
        /*
         * DB already contains the new authoritative photo.
         *
         * A failed cleanup must not make a successful
         * profile update appear unsuccessful.
         */
      });
    }

    return savedProfile;
  } catch (error) {
    try {
      await connection.rollback();
    } catch {
      /*
       * Ignore rollback failure and preserve the original error.
       */
    }

    /*
     * If the DB update failed after the new file was written,
     * remove the orphaned new file.
     */
    if (newFileWritten) {
      await unlink(storedAbsolutePath).catch(() => {
        /*
         * Cleanup failure is intentionally ignored here.
         */
      });
    }

    throw error;
  } finally {
    connection.release();
  }
}
/* ============================================================
   PROFILE PHOTO READ
   ============================================================ */

export interface ProfilePhotoResult {
  buffer: Buffer;
  contentType: "image/jpeg" | "image/png" | "image/webp";
}

/**
 * Load the authenticated user's profile photo.
 *
 * The database is the source of truth for the photo reference.
 * The stored path is validated before any filesystem access.
 */
export async function getProfilePhoto(
  userId: number,
): Promise<ProfilePhotoResult | null> {
  if (!Number.isSafeInteger(userId) || userId <= 0) {
    throw new Error("Invalid user ID.");
  }

  /*
   * Read the profile using the database as the source of truth.
   *
   * We intentionally do not accept a file path from the
   * client/request.
   */
  const [rows]: any = await db.query(
    `
        SELECT profile_photo_path
        FROM applicant_profiles
        WHERE user_id = ?
        LIMIT 1
      `,
    [userId],
  );

  const profilePhotoPath = rows?.[0]?.profile_photo_path
    ? String(rows[0].profile_photo_path)
    : null;

  if (!profilePhotoPath) {
    return null;
  }

  const absolutePath = getSafeStoredFilePath(profilePhotoPath);

  if (!absolutePath) {
    throw new Error("Invalid stored profile photo reference.");
  }

  const extension = path.extname(absolutePath).replace(".", "").toLowerCase();

  const contentTypes: Record<string, ProfilePhotoResult["contentType"]> = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    webp: "image/webp",
  };

  const contentType = contentTypes[extension];

  if (!contentType) {
    throw new Error("Unsupported stored profile photo format.");
  }

  const buffer = await readFile(absolutePath);

  if (!buffer.length || buffer.length > MAX_PROFILE_PHOTO_SIZE) {
    throw new Error("Stored profile photo is invalid.");
  }

  /*
   * Verify the stored file signature as well.
   * This prevents a renamed non-image file from being served.
   */
  const detectedExtension = detectImageExtension(buffer);

  if (
    !detectedExtension ||
    (detectedExtension === "jpg"
      ? contentType !== "image/jpeg"
      : contentType !== `image/${detectedExtension}`)
  ) {
    throw new Error("Stored profile photo content is invalid.");
  }

  return {
    buffer,
    contentType,
  };
}
