import { listAllEmploymentTypes, listAllOrgUnits, listAllBanks, listAllDesignations, listAllStreams, listAllMscBatches, listAllCourses, listAllTraineeBatches, createOrgUnit, updateOrgUnit, setOrgUnitStatus, createBank, updateBank, setBankStatus, createDesignation, updateDesignation, setDesignationStatus, createStream, updateStream, setStreamStatus, createMscBatch, updateMscBatch, setMscBatchStatus, createCourse, updateCourse, setCourseStatus, createTraineeBatch, updateTraineeBatch, setTraineeBatchStatus } from "../repositories/profile-master-admin.repository";
import { db } from "../db/connection";

const ORG_TYPES = new Set(["department", "cell", "project"]);
function text(value: unknown): string { return value == null ? "" : String(value).trim(); }
function required(value: unknown, label: string, max: number): string { const result=text(value); if(!result) throw new Error(`${label} is required.`); if(result.length>max) throw new Error(`${label} cannot exceed ${max} characters.`); return result; }
function id(value: unknown, label: string): number { const result=Number(value); if(!Number.isSafeInteger(result)||result<=0) throw new Error(`${label} must be a valid positive integer.`); return result; }
function year(value: unknown, label: string): number { const result=id(value,label); if(result<1900||result>2200) throw new Error(`${label} must be between 1900 and 2200.`); return result; }
function status(value: unknown): "active"|"inactive" { const result=text(value).toLowerCase(); if(result!=="active"&&result!=="inactive") throw new Error("Status must be active or inactive."); return result; }
async function exists(table:string,column:string,value:unknown,excludeId?:number){const params:unknown[]=[value];const exclude=excludeId?"AND id <> ?":"";if(excludeId)params.push(excludeId);const [rows]:any=await db.query(`SELECT id FROM ${table} WHERE LOWER(TRIM(${column}))=LOWER(TRIM(?)) ${exclude} LIMIT 1`,params);return Boolean(rows?.length);}
async function existsPair(table:string,columns:[string,string],values:[unknown,unknown],excludeId?:number){const params:unknown[]=[...values];const exclude=excludeId?"AND id <> ?":"";if(excludeId)params.push(excludeId);const [rows]:any=await db.query(`SELECT id FROM ${table} WHERE ${columns[0]}=? AND LOWER(TRIM(${columns[1]}))=LOWER(TRIM(?)) ${exclude} LIMIT 1`,params);return Boolean(rows?.length);}
async function fkExists(table:string,value:number){const [rows]:any=await db.query(`SELECT id FROM ${table} WHERE id=? LIMIT 1`,[value]);return Boolean(rows?.length);}
export const listAdminEmploymentTypes=()=>listAllEmploymentTypes();export const listAdminOrgUnits=()=>listAllOrgUnits();export const listAdminBanks=()=>listAllBanks();export const listAdminDesignations=()=>listAllDesignations();export const listAdminStreams=()=>listAllStreams();export const listAdminMscBatches=()=>listAllMscBatches();export const listAdminCourses=()=>listAllCourses();export const listAdminTraineeBatches=()=>listAllTraineeBatches();
export async function addOrgUnit(input:any){const unitType=text(input?.unitType).toLowerCase();if(!ORG_TYPES.has(unitType))throw new Error("Invalid organization type.");const unitName=required(input?.unitName,"Organization Name",255);const unitCode=required(input?.unitCode,"Organization Code",50).toUpperCase();if(await existsPair("profile_org_units",["unit_type","unit_name"],[unitType,unitName]))throw new Error("An organization with the same name already exists for this type.");if(await existsPair("profile_org_units",["unit_type","unit_code"],[unitType,unitCode]))throw new Error("An organization with the same code already exists for this type.");return createOrgUnit({unitType:unitType as any,unitName,unitCode,description:text(input?.description)||null});}
export async function editOrgUnit(value:unknown,input:any){const recordId=id(value,"Organization ID");const unitType=text(input?.unitType).toLowerCase();if(!ORG_TYPES.has(unitType))throw new Error("Invalid organization type.");const unitName=required(input?.unitName,"Organization Name",255);const unitCode=required(input?.unitCode,"Organization Code",50).toUpperCase();if(await existsPair("profile_org_units",["unit_type","unit_name"],[unitType,unitName],recordId))throw new Error("An organization with the same name already exists for this type.");if(await existsPair("profile_org_units",["unit_type","unit_code"],[unitType,unitCode],recordId))throw new Error("An organization with the same code already exists for this type.");const updated=await updateOrgUnit(recordId,{unitType:unitType as any,unitName,unitCode,description:text(input?.description)||null});if(!updated)throw new Error("Organization not found.");return updated;}
export async function changeOrgUnitStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Organization ID");const next=status(valueStatus);await setOrgUnitStatus(recordId,next);return{id:recordId,status:next};}
export async function addBank(input:any){const bankName=required(input?.bankName,"Bank Name",200);const bankCode=required(input?.bankCode,"Bank Code",50).toUpperCase();if(await exists("profile_bank_masters","bank_name",bankName))throw new Error("A bank with the same name already exists.");if(await exists("profile_bank_masters","bank_code",bankCode))throw new Error("A bank with the same code already exists.");return createBank({bankName,bankCode});}
export async function editBank(value:unknown,input:any){const recordId=id(value,"Bank ID");const bankName=required(input?.bankName,"Bank Name",200);const bankCode=required(input?.bankCode,"Bank Code",50).toUpperCase();if(await exists("profile_bank_masters","bank_name",bankName,recordId))throw new Error("A bank with the same name already exists.");if(await exists("profile_bank_masters","bank_code",bankCode,recordId))throw new Error("A bank with the same code already exists.");const updated=await updateBank(recordId,{bankName,bankCode});if(!updated)throw new Error("Bank not found.");return updated;}
export async function changeBankStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Bank ID");const next=status(valueStatus);await setBankStatus(recordId,next);return{id:recordId,status:next};}
export async function addDesignation(input:any){const employmentTypeId=id(input?.employmentTypeId,"Employment Type");if(!(await fkExists("profile_employment_types",employmentTypeId)))throw new Error("Selected employment type is invalid.");const designationName=required(input?.designationName,"Designation Name",200);const designationCode=required(input?.designationCode,"Designation Code",50).toUpperCase();if(await existsPair("profile_designation_masters",["employment_type_id","designation_name"],[employmentTypeId,designationName]))throw new Error("This designation already exists for the selected employment type.");if(await existsPair("profile_designation_masters",["employment_type_id","designation_code"],[employmentTypeId,designationCode]))throw new Error("This designation code already exists for the selected employment type.");return createDesignation({employmentTypeId,designationName,designationCode});}
export async function editDesignation(value:unknown,input:any){const recordId=id(value,"Designation ID");const employmentTypeId=id(input?.employmentTypeId,"Employment Type");if(!(await fkExists("profile_employment_types",employmentTypeId)))throw new Error("Selected employment type is invalid.");const designationName=required(input?.designationName,"Designation Name",200);const designationCode=required(input?.designationCode,"Designation Code",50).toUpperCase();if(await existsPair("profile_designation_masters",["employment_type_id","designation_name"],[employmentTypeId,designationName],recordId))throw new Error("This designation already exists for the selected employment type.");if(await existsPair("profile_designation_masters",["employment_type_id","designation_code"],[employmentTypeId,designationCode],recordId))throw new Error("This designation code already exists for the selected employment type.");const updated=await updateDesignation(recordId,{employmentTypeId,designationName,designationCode});if(!updated)throw new Error("Designation not found.");return updated;}
export async function changeDesignationStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Designation ID");const next=status(valueStatus);await setDesignationStatus(recordId,next);return{id:recordId,status:next};}
export async function addStream(input:any){const streamName=required(input?.streamName,"Stream Name",200);const streamCode=required(input?.streamCode,"Stream Code",50).toUpperCase();if(await exists("profile_stream_masters","stream_name",streamName))throw new Error("A stream with the same name already exists.");if(await exists("profile_stream_masters","stream_code",streamCode))throw new Error("A stream with the same code already exists.");return createStream({streamName,streamCode});}
export async function editStream(value:unknown,input:any){const recordId=id(value,"Stream ID");const streamName=required(input?.streamName,"Stream Name",200);const streamCode=required(input?.streamCode,"Stream Code",50).toUpperCase();if(await exists("profile_stream_masters","stream_name",streamName,recordId))throw new Error("A stream with the same name already exists.");if(await exists("profile_stream_masters","stream_code",streamCode,recordId))throw new Error("A stream with the same code already exists.");const updated=await updateStream(recordId,{streamName,streamCode});if(!updated)throw new Error("Stream not found.");return updated;}
export async function changeStreamStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Stream ID");const next=status(valueStatus);await setStreamStatus(recordId,next);return{id:recordId,status:next};}
async function validateBatchInput(input:any,type:"msc"|"trainee",excludeId?:number){const parentId=id(type==="msc"?input?.streamId:input?.courseId,type==="msc"?"Stream":"Course");const parentTable=type==="msc"?"profile_stream_masters":"profile_course_masters";if(!(await fkExists(parentTable,parentId)))throw new Error(`Selected ${type==="msc"?"stream":"course"} is invalid.`);const batchNumber=id(input?.batchNumber,"Batch Number");const batchName=required(input?.batchName,"Batch Name",100);const batchCode=required(input?.batchCode,"Batch Code",50).toUpperCase();const validityStartYear=year(input?.validityStartYear,"Validity From");const validityEndYear=year(input?.validityEndYear,"Validity To");if(validityEndYear<validityStartYear)throw new Error("Validity To cannot be earlier than Validity From.");const table=type==="msc"?"profile_msc_batches":"profile_trainee_batches";const parentColumn=type==="msc"?"stream_id":"course_id";if((await db.query(`SELECT id FROM ${table} WHERE ${parentColumn}=? AND batch_number=? ${excludeId?"AND id <> ?":""} LIMIT 1`,excludeId?[parentId,batchNumber,excludeId]:[parentId,batchNumber]))[0]?.length)throw new Error("This batch number already exists for the selected parent.");if((await db.query(`SELECT id FROM ${table} WHERE LOWER(TRIM(batch_code))=LOWER(TRIM(?)) ${excludeId?"AND id <> ?":""} LIMIT 1`,excludeId?[batchCode,excludeId]:[batchCode]))[0]?.length)throw new Error("This batch code already exists.");return{parentId,batchNumber,batchName,batchCode,validityStartYear,validityEndYear};}
export async function addMscBatch(input:any){const d=await validateBatchInput(input,"msc");return createMscBatch({streamId:d.parentId,batchNumber:d.batchNumber,batchName:d.batchName,batchCode:d.batchCode,validityStartYear:d.validityStartYear,validityEndYear:d.validityEndYear});}
export async function editMscBatch(value:unknown,input:any){const recordId=id(value,"MSc Batch ID");const d=await validateBatchInput(input,"msc",recordId);const updated=await updateMscBatch(recordId,{streamId:d.parentId,batchNumber:d.batchNumber,batchName:d.batchName,batchCode:d.batchCode,validityStartYear:d.validityStartYear,validityEndYear:d.validityEndYear});if(!updated)throw new Error("MSc batch not found.");return updated;}
export async function changeMscBatchStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"MSc Batch ID");const next=status(valueStatus);await setMscBatchStatus(recordId,next);return{id:recordId,status:next};}
export async function addCourse(input:any){const courseName=required(input?.courseName,"Course Name",200);const courseCode=required(input?.courseCode,"Course Code",50).toUpperCase();if(await exists("profile_course_masters","course_name",courseName))throw new Error("A course with the same name already exists.");if(await exists("profile_course_masters","course_code",courseCode))throw new Error("A course with the same code already exists.");return createCourse({courseName,courseCode});}
export async function editCourse(value:unknown,input:any){const recordId=id(value,"Course ID");const courseName=required(input?.courseName,"Course Name",200);const courseCode=required(input?.courseCode,"Course Code",50).toUpperCase();if(await exists("profile_course_masters","course_name",courseName,recordId))throw new Error("A course with the same name already exists.");if(await exists("profile_course_masters","course_code",courseCode,recordId))throw new Error("A course with the same code already exists.");const updated=await updateCourse(recordId,{courseName,courseCode});if(!updated)throw new Error("Course not found.");return updated;}
export async function changeCourseStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Course ID");const next=status(valueStatus);await setCourseStatus(recordId,next);return{id:recordId,status:next};}
export async function addTraineeBatch(input:any){const d=await validateBatchInput(input,"trainee");return createTraineeBatch({courseId:d.parentId,batchNumber:d.batchNumber,batchName:d.batchName,batchCode:d.batchCode,validityStartYear:d.validityStartYear,validityEndYear:d.validityEndYear});}
export async function editTraineeBatch(value:unknown,input:any){const recordId=id(value,"Trainee Batch ID");const d=await validateBatchInput(input,"trainee",recordId);const updated=await updateTraineeBatch(recordId,{courseId:d.parentId,batchNumber:d.batchNumber,batchName:d.batchName,batchCode:d.batchCode,validityStartYear:d.validityStartYear,validityEndYear:d.validityEndYear});if(!updated)throw new Error("Trainee batch not found.");return updated;}
export async function changeTraineeBatchStatus(value:unknown,valueStatus:unknown){const recordId=id(value,"Trainee Batch ID");const next=status(valueStatus);await setTraineeBatchStatus(recordId,next);return{id:recordId,status:next};}
