import React, { useEffect, useMemo, useState } from "react";
import { ApplicantProfile, RequisitionRecord, UserRole } from "@/types";
import { OFFICIAL_ROLES } from "@/constants/roles";
import { getFacilities, type FacilityApiRecord } from "@/api/facilities.api";
import { getServices, type ServiceApiRecord } from "@/api/services.api";
import { MasterDrivenQuickApplyModal, type ServiceScope } from "@/features/applicant/forms/MasterDrivenQuickApplyModal";
import { STATIC_ACCESS_ITEMS } from "@/features/access/components/StaticAccessCatalog";
import { BadgeCheck, Building2, Clock3, FlaskConical, Mail, PlusCircle, RefreshCw, ShieldCheck, Wifi, Wrench } from "lucide-react";

interface Props { applicantProfile: ApplicantProfile; currentRole?: UserRole; requisitions: RequisitionRecord[]; onSelectRequisition: (req: RequisitionRecord) => void; onSubmitRequisition?: (req: RequisitionRecord) => void; onNavigateTab?: (tab: string) => void; }
type ModalState = { service?: ServiceApiRecord; facility?: FacilityApiRecord; scope: ServiceScope; mode: "new" | "renewal" } | null;
type AccessItem = { key: string; title: string; subtitle: string; emptyTitle: string; description: string; buttonLabel: string; scope: ServiceScope; kind: "service" | "facility"; color: string; icon: React.ElementType; record: ServiceApiRecord | FacilityApiRecord };

const normalize = (value: unknown) => String(value || "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
const applyName = (name: string) => { const value = String(name || "").trim(); return value.split(/[.(,]/)[0].trim() || value; };
const serviceKind = (name: string) => { const value = normalize(name); if (/email|webmail|mail/.test(value)) return "email"; if (/wifi|wi fi|internet|mac|network/.test(value)) return "mac"; if (/hrms|pms|biometric|attendance/.test(value)) return "hrms"; return "other"; };
const findStatic = (record: ServiceApiRecord | FacilityApiRecord) => STATIC_ACCESS_ITEMS.find((item) => item.kind === ("manager" in record ? "service" : "facility") && (("manager" in record && /email|webmail|mail/.test(normalize(`${record.id} ${record.name}`)) && item.key === "official-wii-email") || ("manager" in record && /wifi|wi fi|internet|mac|network/.test(normalize(`${record.id} ${record.name}`)) && item.key === "campus-internet-mac") || ("manager" in record && /hrms|pms|biometric|attendance/.test(normalize(`${record.id} ${record.name}`)) && item.key === "hrms-biometric") || ("manager" in record && /smart.*identity|smart.*id|rfid|identity card/.test(normalize(`${record.id} ${record.name}`)) && item.key === "smart-id-card") || (!("manager" in record) && /lab|laboratory|research facility/.test(normalize(`${record.id} ${record.name}`)) && item.key === "research-laboratory")));
const matchesService = (req: RequisitionRecord, service: ServiceApiRecord, scope: ServiceScope) => { if (req.selectedServiceKey === service.id || req.selectedRefId === service.id || req.serviceName === service.name) return true; if (scope === "email") return Boolean(req.itHrmsDetails?.requestEmail); if (scope === "mac") return Boolean(req.itHrmsDetails?.requestInternet); if (scope === "hrms") return Boolean(req.itHrmsDetails?.requestHrmsPms || req.itHrmsDetails?.requestBiometric); return req.type === "COMBINED"; };
const matchesFacility = (req: RequisitionRecord, facility: FacilityApiRecord) => req.selectedRefId === facility.id || req.selectedServiceKey === facility.id || (req.labAccessDetails || []).some((lab) => lab.labId === facility.id);
const StatusBadge = ({ state }: { state: "pending" | "approved" | "none" }) => state === "pending" ? <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-amber-50 text-amber-700 border border-amber-200">Requisition Pending</span> : state === "approved" ? <span className="text-[10px] font-bold px-2.5 py-1 rounded-full bg-emerald-50 text-emerald-700 border border-emerald-200">Provisioned</span> : null;

export const MasterDrivenAccessHub: React.FC<Props> = ({ applicantProfile, currentRole = "applicant", requisitions, onSelectRequisition, onSubmitRequisition }) => {
  const [services, setServices] = useState<ServiceApiRecord[]>([]); const [facilities, setFacilities] = useState<FacilityApiRecord[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState<string | null>(null); const [modal, setModal] = useState<ModalState>(null); const roleInfo = OFFICIAL_ROLES.find((role) => role.id === currentRole) || OFFICIAL_ROLES[0];
  useEffect(() => { let cancelled = false; Promise.all([getServices(), getFacilities()]).then(([s, f]) => { if (!cancelled) { setServices(s.services || []); setFacilities(f.facilities || []); } }).catch((err) => { console.error("Failed to load Access masters:", err); if (!cancelled) setError("Unable to load Facilities & Services Master records."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, []);

  const items = useMemo<AccessItem[]>(() => {
    const activeServices = services.filter((s) => String(s.status || "active").toLowerCase() === "active").map((service) => { const kind = serviceKind(service.name); const staticItem = findStatic(service); const scope: ServiceScope = staticItem?.scope || (kind === "email" ? "email" : kind === "mac" ? "mac" : "combined"); const Icon = staticItem?.icon || (kind === "email" ? Mail : kind === "mac" ? Wifi : Wrench); return { key: `service-${service.id}`, title: service.name, subtitle: (kind === "email" || kind === "mac") ? service.quota || "" : "", emptyTitle: staticItem?.emptyTitle || `No Active ${service.name}`, description: staticItem?.description || `Apply for ${service.name} through the WII Access Management Portal.`, buttonLabel: `Apply for ${applyName(service.name)}`, scope, kind: "service" as const, color: staticItem?.color || "bg-blue-600", icon: Icon, record: service }; });
    const activeFacilities = facilities.filter((f) => String(f.status || "active").toLowerCase() === "active").map((facility) => { const staticItem = findStatic(facility); return { key: `facility-${facility.id}`, title: facility.name, subtitle: staticItem?.subtitle || facility.dept || "", emptyTitle: staticItem?.emptyTitle || `No Active ${facility.name} Access`, description: staticItem?.description || facility.desc || `Apply for ${facility.name} through the WII Access Management Portal.`, buttonLabel: `Apply for ${applyName(facility.name)}`, scope: "lab" as ServiceScope, kind: "facility" as const, color: staticItem?.color || "bg-teal-600", icon: staticItem?.icon || FlaskConical, record: facility }; });
    return [...activeServices, ...activeFacilities];
  }, [services, facilities]);

  const userReqs = useMemo(() => requisitions.filter((r) => r.applicant?.personalEmail === applicantProfile.personalEmail || r.applicant?.applicantName === applicantProfile.applicantName), [requisitions, applicantProfile.personalEmail, applicantProfile.applicantName]);
  const approved = userReqs.filter((r) => r.status === "approved_provisioned"); const pending = userReqs.filter((r) => !["approved_provisioned", "rejected", "deactivated"].includes(r.status));
  const requestFor = (item: AccessItem) => { if (item.kind === "service") { const s = item.record as ServiceApiRecord; const a = approved.find((r) => matchesService(r, s, item.scope)); if (a) return { state: "approved" as const, req: a }; const p = pending.find((r) => matchesService(r, s, item.scope)); return p ? { state: "pending" as const, req: p } : { state: "none" as const, req: undefined }; } const f = item.record as FacilityApiRecord; const a = approved.find((r) => matchesFacility(r, f)); if (a) return { state: "approved" as const, req: a }; const p = pending.find((r) => matchesFacility(r, f)); return p ? { state: "pending" as const, req: p } : { state: "none" as const, req: undefined }; };

  const renderState = (item: AccessItem, state: "pending" | "approved" | "none", req?: RequisitionRecord) => { const Icon = item.icon; if (state === "pending") return <div className="min-h-[190px] rounded-xl border border-amber-300 bg-amber-50 flex flex-col items-center justify-center text-center px-5 py-8"><div className="w-10 h-10 rounded-full bg-white border border-amber-200 flex items-center justify-center mb-3"><Clock3 className="w-5 h-5 text-amber-600" /></div><div className="text-sm font-extrabold text-amber-900">Requisition Pending Verification</div><p className="max-w-[650px] text-[11px] text-slate-600 mt-1.5">Requisition <b className="font-mono">{req?.id}</b> is currently under workflow review.</p><button type="button" onClick={() => req && onSelectRequisition(req)} className="mt-4 text-xs font-extrabold text-blue-700">View Requisition Status →</button></div>; if (state === "approved") return <div className="min-h-[190px] rounded-xl border border-emerald-200 bg-emerald-50 flex flex-col items-center justify-center text-center px-5 py-8"><div className="w-10 h-10 rounded-full bg-white border border-emerald-200 flex items-center justify-center mb-3"><BadgeCheck className="w-5 h-5 text-emerald-600" /></div><div className="text-sm font-extrabold text-emerald-900">Active Access</div><p className="max-w-[650px] text-[11px] text-slate-600 mt-1.5">Access is provisioned under requisition <b className="font-mono">{req?.id}</b>.</p><button type="button" onClick={() => setModal({ ...(item.kind === "service" ? { service: item.record as ServiceApiRecord } : { facility: item.record as FacilityApiRecord }), scope: item.scope, mode: "renewal" })} className="mt-4 inline-flex items-center gap-1.5 px-4 py-2.5 rounded-lg border border-blue-200 bg-white text-blue-700 text-xs font-bold"><RefreshCw className="w-3.5 h-3.5" />Renew</button></div>; return <div className="min-h-[190px] rounded-xl border border-dashed border-slate-300 bg-slate-50/70 flex flex-col items-center justify-center text-center px-5 py-8"><div className="w-10 h-10 rounded-full border border-slate-200 bg-white flex items-center justify-center mb-3"><Icon className="w-5 h-5 text-blue-600" /></div><div className="text-sm font-extrabold text-slate-900">{item.emptyTitle}</div><p className="max-w-[650px] text-[11px] text-slate-500 mt-1.5">{item.description}</p><button type="button" onClick={() => setModal({ ...(item.kind === "service" ? { service: item.record as ServiceApiRecord } : { facility: item.record as FacilityApiRecord }), scope: item.scope, mode: "new" })} className={`mt-4 inline-flex items-center gap-1.5 px-4 py-2.5 rounded-lg text-xs font-bold text-white shadow-sm ${item.color}`}><PlusCircle className="w-3.5 h-3.5" />{item.buttonLabel}</button></div>; };

  return <div className="space-y-5 max-w-[1520px] mx-auto pb-8">{error && <div className="p-4 rounded-xl bg-red-50 border border-red-200 text-red-700 text-xs font-semibold">{error}</div>}{loading ? <div className="p-12 text-center bg-white border border-slate-200 rounded-xl text-xs text-slate-500">Loading Access...</div> : <>{items.map((item) => { const request = requestFor(item); return <article key={item.key} className="bg-white rounded-xl border border-slate-200 overflow-hidden shadow-sm"><div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between gap-4"><div className="flex items-center gap-4 min-w-0"><div className={`w-11 h-11 rounded-lg flex items-center justify-center shrink-0 ${item.color}`}><item.icon className="w-5 h-5 text-white" /></div><div className="min-w-0"><h3 className="text-[15px] font-extrabold text-slate-900">{item.title}</h3>{item.subtitle && <p className="text-[11px] text-blue-700/80 mt-1">{item.subtitle}</p>}</div></div><StatusBadge state={request.state} /></div><div className="p-5 sm:p-6">{renderState(item, request.state, request.req)}</div></article>; })}{items.length === 0 && <div className="p-12 text-center bg-white border border-dashed border-slate-300 rounded-xl text-xs text-slate-500">No active Facilities or Services are configured in Master.</div>}</>}{modal && <MasterDrivenQuickApplyModal isOpen={true} onClose={() => setModal(null)} serviceScope={modal.scope} mode={modal.mode} applicantProfile={applicantProfile} existingRequisitions={requisitions} onSubmitRequisition={(req) => onSubmitRequisition?.(req)} service={modal.service} facility={modal.facility} />}{roleInfo.title && <div className="hidden"><Building2 /><ShieldCheck /></div>}</div>;
};
